name: Build Swift Project
on:
  push:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Swift Build and List
        run: |
          docker run --rm \
          --workdir /github/workspace \
          -v ${{ github.workspace }}:/github/workspace \
          swift:5.9.2-windowsservercore-ltsc2022 \
          bash -c "swift build -c release && ls ./.build/release"
