name: Build Swift Project
on:
  push:

jobs:
  swift_for_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: MaxDesiatov/swift-windows-action@v1
        with:
          shell-action: swift build -c release
      - run: ls ./.build/release/
