name: Build Swift Project
on:
  push:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - run: pwd

      - name: Swift Build and List
        run: docker run --rm -w /swift-project swift:5.9.2-windowsservercore-ltsc2022 bash -c "pwd && ls && swift --version"
