name: Build
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: swift:5.9.2-windowsservercore-ltsc2022
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: swift build
        run: swift build -c release
      - name: ls
        run: ls -a ./.build/release